#!/bin/bash
HERE=`pwd`

QEMU_NAME=qemu-2.8.0

QEMU_TAR_NAME=${QEMU_NAME}.tar.xz

rm -rf ${QEMU_NAME}
if [ ! -e tainted_qemu ]; then
  echo tainted_qemu directory must exist 
  exit 1
fi
tar xvf ${QEMU_TAR_NAME}
diff -Naur ${QEMU_NAME} tainted_qemu > tmp_cloonix_patch
rm -rf ${QEMU_NAME}
