#!/bin/bash
set -e
HERE=`pwd`
CLOONIX_COMMON=${HERE}/../../../cloonix/common
TARGET=${CLOONIX_COMMON}/spice/spice_lib
if [ ! -d ${TARGET} ]; then
  echo
  echo NOT FOUND:
  echo ${TARGET}
  echo
  exit
fi

cd ${HERE}/spice_client
./patched_create
mv tainted_spice spice_client
rm -rf ${TARGET}/spice_client
mv spice_client ${TARGET}


SPICE_LIB=/usr/local/bin/cloonix/common/spice/spice_lib


PREFIX=/usr/local/bin/cloonix/gtk3
if [ -e ${PREFIX} ]; then
  cd ${TARGET}/spice_client/po
  rm -f Makefile.in.in
  ln -s /usr/local/bin/cloonix/gtk3/share/intltool/Makefile.in.in Makefile.in.in
  cd ${TARGET}/spice_client
  export PATH="${PREFIX}/bin:$PATH"
  export C_INCLUDE_PATH="${PREFIX}/include"
  export CFLAGS="-I${PREFIX}/include"
  export LDFLAGS="-L${PREFIX}/lib"
  export PKG_CONFIG_PATH="${TARGET}/pkgconfig:${PREFIX}/lib/pkgconfig"
  export PKG_CONFIG_LIBDIR=$PKG_CONFIG_PATH
else
  cd ${TARGET}/spice_client
  export PKG_CONFIG_PATH=${TARGET}/pkgconfig 
fi
set +e
  export NOCONFIGURE=no
  ./autogen.sh 
set -e
  ./configure --prefix=${TARGET} \
              --libdir=${TARGET} \
              --datarootdir=${TARGET} \
              --with-usb-acl-helper-dir=${SPICE_LIB} \
              --enable-polkit \
              --enable-usbredir \
              --disable-gtk-doc \
              --disable-gtk-doc-html \
              --disable-gtk-doc-pdf \
              --disable-controler \
              --disable-dbus \
              --disable-vala \
              --disable-webdav \
              --disable-smartcard \
              --disable-lz4

sed -i s"/controller//" src/Makefile
make clean
make
for i in Makefile doc/Makefile data/Makefile man/Makefile src/Makefile src/controller/Makefile; do
  sed -i s"%POLICYDIR = .*%POLICYDIR = ${TARGET}%" $i
  sed -i s"%ACL_HELPER_DIR = .*%ACL_HELPER_DIR = ${TARGET}%" $i
done
make install


