#!/bin/bash
set -e
HERE=`pwd`
TMPBUILD=${HERE}/tmpbuild
CLOONIX_COMMON=${TMPBUILD}/cloonix/common
CLOONIX_SERVER=${TMPBUILD}/cloonix/server
CLOONIX_CLIENT=${TMPBUILD}/cloonix/client
#----------------------------------------------------------
echo TARGET:
echo $TMPBUILD
#----------------------------------------------------------
rm -rf ${TMPBUILD}
mkdir -p ${TMPBUILD}
cp -r ${HERE}/cloonix ${TMPBUILD}
#----------------------------------------------------------
for i in cloonix_net cloonix_ssh cloonix_scp \
         cloonix_cli  cloonix_gui cloonix_zor; do
  mv ${TMPBUILD}/cloonix/${i} ${TMPBUILD}
done
#----------------------------------------------------------
  echo
  echo BUILDING COMMON
  echo
  sleep 1
#----------------------------------------------------------
  cd ${CLOONIX_COMMON}/agent_dropbear
  ./cmd_alien
  ./cmd
#----------------------------------------------------------
  cd ${CLOONIX_COMMON}/spice
  ./cmd
#----------------------------------------------------------
  for i in lib_rpc_clownix \
           lib_utils \
           lib_rpc_qmonitor \
           lib_rpc_doors \
           lib_rpc_c2c \
           lib_rpc_layout ; do

    cd ${CLOONIX_COMMON}/${i}
    echo
    echo DOING:
    echo ${CLOONIX_COMMON}/${i}
    echo
    echo
    make clean
    make -j 5

  done
#----------------------------------------------------------
  echo
  echo BUILDING SERVER
  echo
  sleep 1
#----------------------------------------------------------
  for i in  doorways \
            uml_cloonix_switch \
            qmonitor \
            muswitch/lib_ioc \
            muswitch/lib_mulan \
            muswitch/lib_muend \
            muswitch/mutap \
            muswitch/musnf \
            muswitch/munat/clo_tcp \
            muswitch/munat \
            muswitch/muc2c \
            muswitch/mua2b \
            muswitch/mulan ; do

    echo
    echo DOING:
    echo ${CLOONIX_SERVER}/${i}
    echo
    echo
    cd ${CLOONIX_SERVER}/${i}
    make clean
    make -j 5

  done

  cd ${CLOONIX_SERVER}/spice
  ./cmd

  cd ${CLOONIX_SERVER}/qemu
  ./cmd

#----------------------------------------------------------
  echo
  echo BUILDING CLIENT
  echo
  PREFIX=/usr/local/bin/cloonix/gtk3
  if [ -e ${PREFIX} ]; then
    export PATH="${PREFIX}/bin:$PATH"
    export C_INCLUDE_PATH=${PREFIX}/include
    export PKG_CONFIG_PATH=${PREFIX}/lib/pkgconfig
    export PKG_CONFIG_LIBDIR=${PREFIX}/lib/pkgconfig
    export CFLAGS=-I${PREFIX}/include
    export LDFLAGS=-L${PREFIX}/lib
  fi
  sleep 1
#----------------------------------------------------------
  cd ${CLOONIX_CLIENT}/lib_client
  make clean
  make libglibclient.a
  make

  for i in  ctrl \
            cairo_canvas/crcanvas_gtk \
            cairo_canvas/src/bank \
            cairo_canvas/src/interface \
            cairo_canvas/src/subsets \
            cairo_canvas \
            lib_zor \
            hyperzor ; do

    echo
    echo DOING:
    echo ${CLOONIX_CLIENT}/${i}
    echo
    echo
    cd ${CLOONIX_CLIENT}/${i}
    make clean
    make -j 5

  done

  cd ${CLOONIX_CLIENT}/spice
  ./cmd
#----------------------------------------------------------

