#!/bin/bash
HERE=`pwd`
#----------------------------------------------------------
if [ $# != 1 ]; then
  echo Give cloonix to install as param
  exit
fi
#----------------------------------------------------------
CLOONIX=$1
if [ ! -e $CLOONIX ]; then
  echo NOT FOUND:
  echo $CLOONIX
  exit
fi
#----------------------------------------------------------
rm -rf /usr/local/bin/cloonix*
cd /usr/local/bin
tar zxvf ${HERE}/${CLOONIX}
chown -R root:root /usr/local/bin/cloonix*
MUTAP=/usr/local/bin/cloonix/server/muswitch/mutap/cloonix_mutap
chmod u+s ${MUTAP}
#----------------------------------------------------------
