#!/bin/bash
set -e
HERE=`pwd`
CLOONIX_COMMON=${HERE}/../../../cloonix/common
PKGCONFIG=${CLOONIX_COMMON}/spice/spice_lib/pkgconfig
PREFIX=/usr/local/bin/cloonix/gtk3
if [ -e ${PREFIX} ]; then
  PKGCONFIG+=:${PREFIX}/lib/pkgconfig
  export PATH="${PREFIX}/bin:$PATH"
  export C_INCLUDE_PATH=${PREFIX}/include
  export PKG_CONFIG_PATH=${PKGCONFIG}
  export PKG_CONFIG_LIBDIR=${PKGCONFIG}
  export CFLAGS="-I${PREFIX}/include"
  export LDFLAGS="-L${PREFIX}/lib \
                  -Wl,-rpath=${PREFIX}/lib \
                  -L${CLOONIX_COMMON}/spice/spice_lib \
                  -Wl,-rpath=${CLOONIX_COMMON}/spice/spice_lib" ;
else
  export PKG_CONFIG_PATH=${PKGCONFIG}
  export LDFLAGS="-L${CLOONIX_COMMON}/spice/spice_lib \
                  -Wl,-rpath=${CLOONIX_COMMON}/spice/spice_lib" ;
fi
MUETH=${HERE}/../../
QEMU_NAME=qemu-627eae7
rm -rf ${HERE}/qemu_bin
mkdir -p ${HERE}/qemu_bin

cd ${HERE}/sources
./patched_create
mv tainted_qemu ${HERE}/qemu_bin
cd ${HERE}/qemu_bin/tainted_qemu


#                     --disable-xen-pv-domain-build
#                     --disable-xen
#                     --disable-xen-pci-passthrough
 CONFIGURATION_OPTS="--prefix=/usr/local
                     --target-list=x86_64-softmmu
                     --enable-kvm
                     --enable-spice
                     --enable-usb-redir
                     --enable-linux-user
                     --disable-replication
                     --disable-rdma
                     --disable-xen
                     --disable-xen-pci-passthrough
                     --disable-gtk
                     --disable-virtfs
                     --disable-sdl
                     --disable-modules
                     --disable-slirp
                     --disable-tcg-interpreter
                     --disable-user
                     --disable-bsd-user
                     --disable-docs
                     --disable-guest-agent
                     --disable-guest-agent-msi
                     --disable-debug-tcg
                     --disable-debug-info
                     --disable-sparse
                     --disable-gnutls
                     --disable-nettle
                     --disable-gcrypt
                     --disable-vte
                     --disable-curses
                     --disable-vnc
                     --disable-vnc-sasl
                     --disable-vnc-jpeg
                     --disable-vnc-png
                     --disable-cocoa
                     --disable-brlapi
                     --disable-curl
                     --disable-fdt
                     --disable-bluez
                     --disable-rdma
                     --disable-vde
                     --disable-netmap
                     --disable-cap-ng
                     --disable-attr
                     --disable-vhost-net
                     --disable-rbd
                     --disable-libiscsi
                     --disable-libnfs
                     --disable-smartcard
                     --disable-libusb
                     --disable-seccomp
                     --disable-glusterfs
                     --disable-tpm
                     --disable-libssh2
                     --disable-numa
                     --disable-tcmalloc
                     --disable-jemalloc
                     --disable-replication
                     --enable-mueth
                     --muethdir=${MUETH}"

./configure  $CONFIGURATION_OPTS

make clean
make -j 5

mv x86_64-softmmu/qemu-system-x86_64 ${HERE}/qemu_bin
mv qemu-img                     ${HERE}/qemu_bin
cp ./pc-bios/bios-256k.bin      ${HERE}/qemu_bin
cp ./pc-bios/kvmvapic.bin       ${HERE}/qemu_bin
cp ./pc-bios/vgabios.bin        ${HERE}/qemu_bin
cp ./pc-bios/vgabios-stdvga.bin ${HERE}/qemu_bin
cp ./pc-bios/vgabios-qxl.bin    ${HERE}/qemu_bin
cp ./pc-bios/vgabios-vmware.bin ${HERE}/qemu_bin
cp ./pc-bios/efi-virtio.rom     ${HERE}/qemu_bin
cp ./pc-bios/efi-e1000.rom      ${HERE}/qemu_bin
cp ./pc-bios/efi-ne2k_pci.rom   ${HERE}/qemu_bin
cp ./pc-bios/efi-rtl8139.rom    ${HERE}/qemu_bin



