#!/bin/bash

fct_env_gtk3()
{
  PREFIX=/usr/local/bin/cloonix/gtk3
  if [ -e ${PREFIX} ]; then
    export PATH="${PREFIX}/bin:$PATH"
    export C_INCLUDE_PATH=${PREFIX}/include
    export PKG_CONFIG_PATH=${PREFIX}/lib/pkgconfig
    export PKG_CONFIG_LIBDIR=${PREFIX}/lib/pkgconfig
    export CFLAGS=-I${PREFIX}/include
    export LDFLAGS=-L${PREFIX}/lib
  fi
}

fct_env_gtk3

make clean
make libglibclient.a
make

