#!/bin/bash
set -e
HERE=`pwd`
TARGET=${HERE}/spice_lib
rm -rf ${TARGET}
mkdir -p ${TARGET}

fct_env_gtk3()
{
  PREFIX=/usr/local/bin/cloonix/gtk3
  if [ -e ${PREFIX} ]; then
    export PATH="${PREFIX}/bin:$PATH"
    export C_INCLUDE_PATH=${PREFIX}/include
    export PKG_CONFIG_PATH=${PREFIX}/lib/pkgconfig
    export PKG_CONFIG_LIBDIR=${PREFIX}/lib/pkgconfig
    export CFLAGS=-I${PREFIX}/include
    export LDFLAGS=-L${PREFIX}/lib
  fi
}

fct_env_gtk3

cd $TARGET
tar xvf ${HERE}/spice_protocol/spice-protocol.tar.gz
cd spice-protocol
./configure --prefix=${TARGET} \
            --datarootdir=${TARGET}
make clean
make
make install

export PKG_CONFIG_PATH=${TARGET}/pkgconfig
SPICE_PC=${TARGET}/spice-protocol/spice-protocol.pc
mkdir -p $PKG_CONFIG_PATH
cp -f ${SPICE_PC} $PKG_CONFIG_PATH
sed -i s"%prefix}/share%prefix}%" ${PKG_CONFIG_PATH}/spice-protocol.pc

cd ${TARGET}
tar xvf ${HERE}/spice_usb/usbredir.tar.gz
cd usbredir

PREFIX=/usr/local/bin/cloonix/gtk3
if [ -e ${PREFIX} ]; then
  export PATH="${PREFIX}/bin:$PATH"
  export C_INCLUDE_PATH="${PREFIX}/include"
  export CFLAGS="-I${PREFIX}/include"
  export LDFLAGS="-L${PREFIX}/lib"
  export PKG_CONFIG_PATH="${TARGET}/pkgconfig:${PREFIX}/lib/pkgconfig"
  export PKG_CONFIG_LIBDIR=$PKG_CONFIG_PATH
fi

./configure --prefix=${TARGET} --libdir=${TARGET}

make clean
make
make install


