#!/bin/bash
HERE=`pwd`
set -e
AGENT_BIN=${HERE}/agent_bin
rm -rf ${AGENT_BIN}
mkdir -p ${AGENT_BIN}

LIB_CLOWNIX=${HERE}/../lib_io_clownix
BLKD=${HERE}/../lib_blkd
RPCT=${HERE}/../lib_rpct

fct_env_gtk3()
{
  PREFIX=/usr/local/bin/cloonix/gtk3
  if [ -e ${PREFIX} ]; then
    export PATH="${PREFIX}/bin:$PATH"
    export C_INCLUDE_PATH=${PREFIX}/include
    export PKG_CONFIG_PATH=${PREFIX}/lib/pkgconfig
    export PKG_CONFIG_LIBDIR=${PREFIX}/lib/pkgconfig
    export CFLAGS=-I${PREFIX}/include
    export LDFLAGS=-L${PREFIX}/lib
  fi
}

fct_env_gtk3

cd $LIB_CLOWNIX
make clean
make

cd $BLKD
make clean
make

cd $RPCT
make clean
make

cd ${HERE}/cloonix_dropbear
make clean
make

cp scp      ${AGENT_BIN}/dropbear_cloonix_scp
cp dbclient ${AGENT_BIN}/dropbear_cloonix_ssh
cp dropbear ${AGENT_BIN}/dropbear_cloonix_sshd


