#!/bin/bash
HERE=`pwd`

AGENT_BIN_ARM=${HERE}/agent_bin_arm
LIB_CLOWNIX=${HERE}/../lib_io_clownix
BLKD=${HERE}/../lib_blkd
RPCT=${HERE}/../lib_rpct

set -e
rm -rf ${AGENT_BIN_ARM}
mkdir -p ${AGENT_BIN_ARM}

cd $LIB_CLOWNIX
make clean
cd $BLKD
make clean
cd $RPCT
make clean
cd ${HERE}/cloonix_dropbear
make clean
cd ${HERE}/cloonix_agent
make clean


export STAGING_DIR=/home/perrier/lede/staging_dir
CROSS_ARM=${STAGING_DIR}/toolchain-arm_cortex-a9+neon_gcc-5.4.0_musl_eabi
export CC=${CROSS_ARM}/bin/arm-openwrt-linux-gcc
export AR=${CROSS_ARM}/bin/arm-openwrt-linux-gcc-ar
export RANLIB=${CROSS_ARM}/bin/arm-openwrt-linux-ranlib
export CFLAGS="-DNO_HMAC_CIPHER"


cd $LIB_CLOWNIX
make
cd $BLKD
make
cd $RPCT
make
cd ${HERE}/cloonix_dropbear
make dropbear
cp dropbear ${AGENT_BIN_ARM}/dropbear_cloonix_sshd
cd ${HERE}/cloonix_agent
make
cp cloonix_agent ${AGENT_BIN_ARM}

cd $LIB_CLOWNIX
make clean
cd $BLKD
make clean
cd $RPCT
make clean
cd ${HERE}/cloonix_dropbear
make clean
cd ${HERE}/cloonix_agent
make clean


