#!/bin/bash
set -e
HERE=`pwd`
CLOONIX_COMMON=${HERE}/../../../cloonix/common
TARGET=${CLOONIX_COMMON}/spice/spice_lib
if [ ! -d ${TARGET} ]; then
  echo
  echo NOT FOUND:
  echo ${TARGET}
  echo
  exit
fi

#----------------------------------------------------------
cd ${HERE}/spice_server
tar xvf spice.tar.gz
mv spice spice_server
rm -rf ${TARGET}/spice_server
mv spice_server ${TARGET}
cd ${TARGET}/spice_server
export PKG_CONFIG_PATH=${TARGET}/pkgconfig

set +e
  export NOCONFIGURE=yes
  ./autogen.sh
set -e
  ./configure --prefix=${TARGET} \
              --enable-gstreamer=yes \
              --libdir=${TARGET} \
              --datarootdir=${TARGET} \
              --disable-celt051 \
              --disable-smartcard \
              --disable-client \
              --disable-static \
              --disable-lz4

make clean
make
make install

